name: Auto Deploy Spring Boot App

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the Project
        run: mvn clean package -DskipTests

      - name: Verify JAR File Exists (Cross-Platform)
        shell: pwsh
        run: |
          if (!(Test-Path -Path "target" -PathType Container)) {
            Write-Host "❌ No target directory found!"
            exit 1
          }

          $jarFile = Get-ChildItem -Path "target" -Filter "*.jar" | Select-Object -First 1

          if ($null -eq $jarFile) {
            Write-Host "❌ No JAR file found in target/! Exiting..."
            exit 1
          }

          Write-Host "✅ Found JAR file: $jarFile"
          echo "JAR_FILE=$($jarFile.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        shell: pwsh
        run: |
          $jarFile = $env:JAR_FILE
          if (!$jarFile) {
            Write-Host "❌ JAR file path not set!"
            exit 1
          }

          Write-Host "✅ Using JAR file: $jarFile"
          Copy-Item -Path $jarFile -Destination "app.jar"

          $imageTag = "${{ secrets.DOCKER_USERNAME }}/springboot-app:" + (Get-Date -Format "yyyyMMddHHmmss")
          docker build -t $imageTag .
          docker push $imageTag

          Write-Host "✅ Docker Image Pushed: $imageTag"
          echo "IMAGE_TAG=$imageTag" | Out-File -FilePath $env:GITHUB_ENV -Append

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/springboot-app:$(date +%Y%m%d%H%M%S)
            docker pull $IMAGE_TAG
            docker stop springboot-app || true
            docker rm springboot-app || true
            docker run -d --name springboot-app -p 8080:8080 $IMAGE_TAG
