name: Auto Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the Project
        run: mvn clean package -DskipTests

      - name: Verify Target Directory and JAR File
        run: |
          echo "Checking if target directory exists..."
          ls -l target/ || echo "No target directory found!"
          echo "Checking if JAR file exists..."
          find target/ -name "*.jar" || echo "No JAR file found!"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          JAR_FILE=$(find target/ -name "*.jar" | head -n 1)
          if [[ -z "$JAR_FILE" ]]; then
            echo "Error: No JAR file found. Build may have failed."
            exit 1
          fi
          echo "Using JAR file: $JAR_FILE"
          cp "$JAR_FILE" app.jar
          docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
            docker stop springboot-app || true
            docker rm springboot-app || true
            docker run -d --name springboot-app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
